# Generated by Django 4.2.4 on 2023-08-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publication_year', models.PositiveIntegerField()),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(choices=[('read', '읽은 책'), ('reading', '읽고 있는 책'), ('to_read', '읽고 싶은 책')], default='to_read', max_length=20)),
            ],
        ),
    ]
