# Generated by Django 4.2.4 on 2023-08-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
        ),
    ]
